Feature/testes-unitarios
hbseixas/listas-partidas-futebol pull request #13
Opened 2023-11-22 14:49 UTC by hbseixas

2023-11-22 14:50 UTC, hbseixas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Testes unitários](https://trello.com/c/Obfn5RT6/38-testes-unit%C3%A1rios)

2023-11-22 18:04 UTC, silasyudi requested changes

2023-11-22 18:04 UTC, silasyudi commented on src/test/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaServiceTest.java
> +            assertTrue(Math.abs(partidaDto.getPlacarMandante() - partidaDto.getPlacarVisitante()) >= 3);
Pra reforçar esse aspecto de goleada mandante e visitante, pode colocar um time visitante vencendo o jogo também.

2023-11-22 18:04 UTC, silasyudi commented on src/test/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaServiceTest.java
> +            assertTrue(partidaDto.getPlacarMandante() == 0 && partidaDto.getPlacarVisitante() == 0);
assert 0 fica mais clean

```suggestion
            assertEquals(0, partidaDto.getPlacarMandante());
            assertEquals(0, partidaDto.getPlacarVisitante());
```

2023-11-22 18:04 UTC, silasyudi commented on src/test/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaServiceTest.java
> +        List<Partida> partidasPorEstadio = partidas.stream()
Pra evitar criar este tipo de complexidade que não recomendo compartilhar um objeto entre testes.

O ideal seria sempre criar e popular a lista em cada teste, com os itens que fazem sentido àquele teste.

2023-11-22 18:04 UTC, silasyudi commented on src/test/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaServiceTest.java
> +                .filter(partida -> partidaService.isClubeEnvolvidoNaPartida(partida, partidaDto.getClubeMandante())
Não é proibido, mas é um risco se usar um outro método Y em um teste do método X.

Poderia criar aqui uma lista já com valores que vão dar conflito, e criar o dto com a data inválida.

2023-11-22 20:17 UTC, hbseixas commented on src/test/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaServiceTest.java
> +            assertTrue(Math.abs(partidaDto.getPlacarMandante() - partidaDto.getPlacarVisitante()) >= 3);
Feito!

2023-11-22 20:18 UTC, hbseixas commented on src/test/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaServiceTest.java
> +            assertTrue(partidaDto.getPlacarMandante() == 0 && partidaDto.getPlacarVisitante() == 0);
Feito!

2023-11-22 20:18 UTC, hbseixas commented on src/test/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaServiceTest.java
> +                .filter(partida -> partidaService.isClubeEnvolvidoNaPartida(partida, partidaDto.getClubeMandante())
Feito!

2023-11-23 12:48 UTC, silasyudi approved these changes

2023-11-23 12:50 UTC, merged