Criar CRUD
hbseixas/listas-partidas-futebol pull request #2
Opened 2023-11-08 21:08 UTC by hbseixas

2023-11-08 21:10 UTC, hbseixas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar CRUD](https://trello.com/c/eh3HEj6m/16-criar-crud)

2023-11-09 11:34 UTC, silasmeli requested changes

2023-11-09 11:34 UTC, silasmeli commented on src/main/java/com/meli/hseixas/listaspartidasfutebol/controller/PartidaController.java
> +        return ResponseEntity.created(uri).body(partidaCadastrada);
Você pode evitar a necessidade desse URI fazendo assim:

```suggestion
        return new ResponseEntity<PartidaDto>(partidaCadastrada, HttpStatus.CREATED);
```

2023-11-09 11:34 UTC, silasmeli commented on src/main/java/com/meli/hseixas/listaspartidasfutebol/controller/PartidaController.java
> +    public ResponseEntity<PartidaDto> alterarPartida(@PathVariable Long id, @RequestBody Partida partida) {
Deve-se passar um DTO de entrada, e não uma Entity

2023-11-09 11:34 UTC, silasmeli commented on src/main/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaService.java
> +            Partida partida = partidaOptional.get();
pode ter um método para converter de Dto para Entity

2023-11-09 14:30 UTC, hbseixas commented on src/main/java/com/meli/hseixas/listaspartidasfutebol/controller/PartidaController.java
> +        return ResponseEntity.created(uri).body(partidaCadastrada);
Feito

2023-11-09 14:30 UTC, hbseixas commented on src/main/java/com/meli/hseixas/listaspartidasfutebol/controller/PartidaController.java
> +    public ResponseEntity<PartidaDto> alterarPartida(@PathVariable Long id, @RequestBody Partida partida) {
Feito

2023-11-09 14:30 UTC, hbseixas commented on src/main/java/com/meli/hseixas/listaspartidasfutebol/service/PartidaService.java
> +            Partida partida = partidaOptional.get();
Feito

2023-11-09 15:09 UTC, silasmeli approved these changes

2023-11-09 15:12 UTC, merged